CREATE TABLE STUDENT
  (
    ID INTEGER PRIMARY KEY,
    DOB DATE,
    FIRSTNAME     VARCHAR2(255),
    LASTNAME      VARCHAR2(255),
    STUDENTNUMBER VARCHAR2(255)
  );
  
    CREATE SEQUENCE SAMPLE_ID_SEQ MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1
  START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE OR REPLACE TRIGGER SAMPLE_ID_TRIG BEFORE
  INSERT ON STUDENT FOR EACH ROW BEGIN
  SELECT CREATESAMPLEID INTO :NEW.ID FROM DUAL;
END;
  
  CREATE OR REPLACE
FUNCTION CREATESAMPLEID
    RETURN NUMBER
  IS
    SAMPLEID NUMBER;
  BEGIN
    RETURN TO_NUMBER(CONCAT(TO_CHAR(TO_CHAR(SYSDATE, 'YYYY')), SAMPLE_ID_SEQ.NEXTVAL), 99999999);
  EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001,'AN ERROR WAS ENCOUNTERED - '||SQLCODE||' -ERROR- '||SQLERRM);
  END;
  
CREATE OR REPLACE TRIGGER SAMPLE_ID_TRIG BEFORE
  INSERT ON STUDENT FOR EACH ROW BEGIN :new.id := CreateSampleId;
END;

INSERT
INTO STUDENT
  (
    DOB,
    FIRSTNAME,
    LASTNAME,
    STUDENTNUMBER
  )
  VALUES
  (
    NULL,
    'Lance',
    'Reid',
    '9988677'
  );